import mujoco
import mujoco.viewer
import numpy as np
import matplotlib.pyplot as plt
import time

# load XLM model
model = mujoco.MjModel.from_xml_path('2R_robotics.xml') # _struct.MjModel 
                                                        # _struct.so (C file)
data = mujoco.MjData(model)

# pid controller
Kp = 0.4 # Proportional gain
Ki = 0.1  # Integral gain
Kd = 1.0  # Derivative gain

# Define our trajectory (a sinusoidal wave for each joints)
def desired_trajectory(t):
    """
    adjust amplitude and freq
    """
    amplitude = 0.5
    joint1_desired = amplitude * np.sin(0.5*np.pi*t)
    joint2_desired = amplitude * np.cos(0.5*np.pi*t)
    return joint1_desired, joint2_desired

# Computing the control signal generated by PID
def pid_control(target, current, prev_error, integral, dt):
    error = target - current
    integral += error * dt
    derivative = (error - prev_error) / dt
    control_signal = Kp * error + Ki * integral + Kd * derivative
    return control_signal, error, integral

# Launch the simulation
with mujoco.viewer.launch_passive(model, data) as viewer:
    start_time = time.time()
    prev_error = [0, 0]
    integral = [0, 0]

    # logging
    # trajectory1 = []
    # trajectory2 = []
    # signals1 = []
    # signals2 = []

    while viewer.is_running():
        current_time = time.time() - start_time
        dt = model.opt.timestep

        # Get desired joint positions
        q1_desired, q2_desired = desired_trajectory(current_time)

        # Get current joint positions
        q1_current = data.qpos[0]
        q2_current = data.qpos[1]

        # Compute PID control signals
        ctrl1, prev_error[0], integral[0] = pid_control(q1_desired, q1_current, prev_error[0], integral[0], dt)
        ctrl2, prev_error[1], integral[1] = pid_control(q2_desired, q2_current, prev_error[1], integral[1], dt)

        # Apply control signals to actuators
        data.ctrl[0] = ctrl1
        data.ctrl[1] = ctrl2

        # Step the simulation
        mujoco.mj_step(model, data)

        # Sync the viewer
        viewer.sync()

